language: python
python:
- 2.7
before_install:
- travis_retry pip install --upgrade pip setuptools
- travis_retry pip install coveralls
install:
- sudo service postgresql stop
- travis_retry pip install -e .[all]
script:
- "./run-tests.sh"
deploy:
  provider: pypi
  user: inspirehep
  password:
    secure: IUDlVbGlw7QhgmjmQcd8fWItUJgg9P3xYPiFqVCJg5W5GHPHzlj6//NTJtisKRDw/1QLzxNopl9ZKyvXZrQ1xzxgQ7OnYDn6Kabvk74gARZ4TuQfdrWh+qA5Z7jdLL6mqykJNeCsCRCYmNsSljAHKqkt6tLrPDylwessm4o5itM5ndXrpONCf+swlZxIdUFoPrQLRSv5+bd6ZkEs1GkM3/KD2iqddwEEmuSG/sVUIEKxj19aORa2IrKf1McxfMXDWXjNHAZjUBwtEGCRvN8uxgili6OrVyPg+76fi/MTiK3ERC5H86psyyd8oXxdvD0U+ir+fQ9916r7de13AJRiuohc59tWgaElKrTCGP4mFjgtm6P/nyJWk0hkyIuBnGLhSuK5VdWVQwH0ac5w7yc+cKDnDerZXExQ9LIDvVZMAtJL6slU7BAPU0f9QtLGjDcyjPdDs+AR7ASaP+3M1X4AkXjfZ/XPcyHpqSXLt8OksbqXnkyOflAMQcs/cb322eAkAVctB5hx+vDXaLgmQCaN+mrYY7zglofKrJunICRwlzENjVzFeqbdgO0JN8SWK2xTAk5Lg7F31PdmlrW7FGmGqh+RZW7SX9LbC0qYSB47sU269iim/GyMRI3cnMQ63y5gF+6S7Z9TX6k/wgCBCer30InG0sZDeRtNz6Y8RiKQgoA=
  on:
    branch: master
